### ISSUE TITLE
adding a generic uncompress function

### ISSUE THREAD

**Issue by xhdong-umd** [gaborcsardi/zip#1]
I'm using `zip` package in my app now because it doesn't rely on external programs. 

I used to write [a uncompress function that support zip, bz2, gz etc using R internal libraries only](https://gist.github.com/xhdong-umd/6429e7f96735142fa467f3b1daa91a2c) too. Since it's in same spirit, I'm wondering if you think it can be added to `zip` package.

The function was based on `R.utils::decompressFile` but with some important differences, especially that it will not delete input file by default. Originally it was designed to uncompress file, run some function on uncompressed files then delete the uncompressed file. It can also be changed to a function that simply uncompress the input.

If you like the idea I can create a pull request for this.

**Comment by gaborcsardi** [comment]
I think it is a good idea, but `zip` is not the ideal place for it. I think you could create a small `decompress` package that depends on `zip`.

Btw. the licensing is not right, either. The code that you took from `R.utils` is LGPL and `zip` is CC0.

**Comment by xhdong-umd** [comment]
Originally I think it's OK since zip and unzip are often distributed together, but the license difference make it impossible.

I'll try to make a small package though I'm not sure if people will install the package just for decompress, especially when R already support reading compressed file in many places. Your `zip` is different because base R need to rely external programs.

I'll try it anyway, thanks!

I'm not sure if people will install the package just for 1 or 2 function, especially when R already support reading compressed files directly

**Comment by gaborcsardi** [comment]
I think it would be nice. You can also try to auto-detect the format, e.g. something like this: https://github.com/r-lib/desc/blob/2471b4a73828bc4c7869c032dea4a90173ca98f2/R/package-archives.R#L7
